wisk/models.py
# This is the database schema.
from wisk import db

class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    source = db.Column(db.String(25), nullable=False)
    title = db.Column(db.String(250), nullable=False)
    url = db.Column(db.String(250), nullable=False)
    url_to_img = db.Column(db.String(250), nullable=False, default='url_not_found')
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    ds = db.Column(db.String(10), nullable=False)
    summary = db.Column(db.Text, nullable=False)

    # This is to print the object.
    def __repr__(self):
        return f"Article('{self.source}', '{self.title}', '{self.image_file}')"

wisk/articles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from wisk.models import Article

class SubmitArticle(FlaskForm):
    source = StringField('Source', validators=[DataRequired(), Length(min=1, max=25)])
    title = StringField('Title', validators=[DataRequired(), Length(min=1, max=250)])
    url = StringField('URL', validators=[DataRequired(), Length(min=1, max=250)])
    url_to_img = StringField('URL to image', validators=[DataRequired(), Length(min=1, max=250)])
    ds = StringField('Published on', validators=[DataRequired(), Length(min=10, max=10)])
    summary = StringField('Summary', validators=[DataRequired(), Length(min=1, max=2500)])

    # Button.
    submit = SubmitField('Submit')

    # Validate that ds has a length of 10.
    def validate_ds(self, ds):
        if len(ds.data) != 10:
            raise ValidationError('ds should be of length 10. Example 2020-11-20.')

wisk/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from wisk.config import Config

db = SQLAlchemy() # Create a SQLAlchemy instance.

# It allows you to create multiple instances of the application for testing, etc.
# This is a design pattern recommended on the flask documentation.
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config) # Load the configs from config.py.

    db.init_app(app)

    # Importing the Blueprint object from each section.
    from wisk.articles.routes import articles
    from wisk.main.routes import main
    from wisk.errors.handlers import errors

    # After importing the Blueprint, we need to register the same.
    app.register_blueprint(articles)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

wisk/articles/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from wisk import db
from wisk.articles.forms import SubmitArticle
from wisk.models import Article

articles = Blueprint('articles', __name__)

# To submit an article.
# methods is required to accept a form submission.
@articles.route('/submit_article', methods=['GET', 'POST'])
def submit_article():
    form = SubmitArticle()

    if form.validate_on_submit():
        # Create an article based on form submission.
        article = Article(
            source=form.source.data,
            title=form.title.data,
            url=form.url.data,
            url_to_img=form.url_to_img.data,
            ds=form.ds.data,
            summary=form.summary.data)

        # Add the new article in the db.
        db.session.add(article)

        # Commit changes to the db.
        db.session.commit()

        # Dsplay a success message.
        flash(f'Article submitted from {form.source.data}', 'success')

        # Redirect to the home page.
        return redirect(url_for('main.home'))

    return render_template('submit_article.html', title='Submit article', form=form)

@articles.route('/article/<int:article_id>')
def article(article_id):
    article = Article.query.get_or_404(article_id)
    return render_template('article.html', title=article.title, article=article)

# Route to delete an article.
@articles.route("/article/<int:article_id>/delete", methods=['POST'])
def delete_article(article_id):
    article = Article.query.get_or_404(article_id)

    db.session.delete(article)
    db.session.commit()

    flash('Your article has been deleted.', 'success')
    return redirect(url_for('main.home'))

# To show all articles from a particular source.
@articles.route('/source/<string:source_name>')
def source(source_name):
    page = request.args.get('page', 1, type=int)

    # Get the all articles from the requested source and display them on the home page. Newest first.
    # paginate allows you to restrict the number of articles that get displayed on each page.
    articles = Article.query.filter_by(source=source_name)\
        .order_by(Article.ds.desc())\
        .paginate(page=page, per_page=10)

    return render_template('source.html', articles=articles)

wisk/main/routes.py
from flask import render_template, request, Blueprint
from wisk.models import Article

main = Blueprint('main', __name__)

# Home page.
@main.route('/')
def home():
    # Get url parameter.
    page = request.args.get('page', 1, type=int)

    # Get the articles from the db and display them on the home page. Newest first.
    # paginate allows you to restrict the number of articles that get displayed on each page.
    articles = Article.query.order_by(Article.ds.desc()).paginate(page=page, per_page=10)
    return render_template('home.html', articles=articles)

@main.route('/about')
def about():
    return 'This is the about page.'

wisk/templates/article.html
<!-- Inherit the layout page to avoid code duplication. -->
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ article.url_to_img }}" alt="">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('articles.source', source_name=article.source) }}">{{ article.source }}</a>
                <small class="text-muted">{{ article.ds }}</small>
            </div>
            <div>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
            <h2 class="article-title">{{ article.title }}</h2>
            <p class="article-content">{{ article.summary }}</p>
        </div>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete article?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('articles.delete_article', article_id=article.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

wisk/templates/home.html
<!-- Inherit the layout page to avoid code duplication. -->
{% extends "layout.html" %}
{% block content %}
    {% for article in articles.items %}
        <!-- <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ article.url_to_img }}" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('articles.source', source_name=article.source) }}">{{ article.source }}</a>
                    <small class="text-muted">{{ article.ds }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('articles.article', article_id=article.id) }}">{{ article.title }}</a></h2>
                <p class="article-content">{{ article.summary }}</p>
            </div>
        </article> -->
        <div class="card mb-3 rounded-2">
            <img class="card-img-top rounded-2" src="{{ article.url_to_img }}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><a target="_blank" rel="noopener noreferrer" class="article-title" href="{{ article.url }}">{{ article.title }}</a></h5>
              <p class="card-text">{{ article.summary }}</p>
              <p class="card-text"><small class="text-muted">Published on {{ article.ds }}</small></p>
            </div>
        </div>
    {% endfor %}

    <!-- To limit the number of articles displayed per page.
    This will allow you to move across pages. -->
    {% for page_num in articles.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if articles.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

wisk/templates/layout.html
<!-- This is the default layout of all html pages of the applicaton. Parent template that other pages will inhherit from.
    This avoids code duplication across files. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  {% if title %}
    <title>Wisk {{ title }}</title>
  {% else %}
    <title>Wisk</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">wisk</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <!-- <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a> -->
            <!-- <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a> -->
          </div>
          <!-- Navbar Right Side -->
          <!-- <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{ url_for('articles.submit_article') }}">Submit article</a>
          </div> -->
        </div>
      </div>
    </nav>
  </header>

  <main role="main" class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <!-- This is to get flash messages from the application.py file. -->
        {% with messages = get_flashed_messages(with_categories=true) %}
          <!-- Display all messages in case there were any any. -->
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-2"></div>
      <!-- <div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
          </p>
        </div>
      </div> -->
    </div>
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

wisk/templates/source.html
<!-- Inherit the layout page to avoid code duplication. -->
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Articles from {{ articles.items[0].source }}</h1>
    {% for article in articles.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ article.url_to_img }}" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('articles.source', source_name=article.source) }}">{{ article.source }}</a>
                    <small class="text-muted">{{ article.ds }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('articles.article', article_id=article.id) }}">{{ article.title }}</a></h2>
                <p class="article-content">{{ article.summary }}</p>
            </div>
        </article>
    {% endfor %}

    <!-- To limit the number of articles displayed per page.
    This will allow you to move across pages. -->
    {% for page_num in articles.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if articles.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('articles.source', source_name=articles.items[0].source, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('articles.source', source_name=articles.items[0].source, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

wisk/templates/submit_article.html
<!-- Inherit the layout page to avoid code duplication. -->
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            <!-- hidden_tag is for some protection. Do not worry about the details. -->
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Submit article</legend>
                <div class="form-group">
                    {{ form.source.label(class="form-control-label") }}

                    {% if form.source.errors %}
                        {{ form.source(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.source.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.source(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}

                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.url.label(class="form-control-label") }}

                    {% if form.url.errors %}
                        {{ form.url(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.url.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.url(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.url_to_img.label(class="form-control-label") }}

                    {% if form.url_to_img.errors %}
                        {{ form.url_to_img(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.url_to_img.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.url_to_img(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.ds.label(class="form-control-label") }}

                    {% if form.ds.errors %}
                        {{ form.ds(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.ds.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.ds(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.summary.label(class="form-control-label") }}

                    {% if form.summary.errors %}
                        {{ form.summary(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.summary.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.summary(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}